services:
  awesome_recipe_cookbook:
    image: ghcr.io/cookbookio/awsome_recipe_cookbook:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge


      