services:
  awesome_recipe_cookbook-production:
    image: ghcr.io/cookbookio/awsome_recipe_cookbook_linting:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
